improve extension API documentation and resolve some open questions
eclipse-ee4j/cdi pull request #520
Opened 2021-09-10 11:36 UTC by Ladicek

- documentation added for synthetic beans and observers; this was
  the last place where proper documentation was missing
- `DeclarationConfig` is no longer generic and `{Class,Method,Field}Config`
  explicitly override the configuration methods, so that users don't have to
  declare a useless type argument when using `DeclarationConfig`
- `AnnotationMember.as*` methods don't perform type conversions
- added `MethodInfo.isConstructor` to distinguish constructors
  from regular methods

2021-09-10 11:38 UTC, Ladicek commented
Sorry for not getting to this sooner, I was occupied elsewhere. This adds documentation to the last undocumented part of the extension API -- synthetic components. This means that the extension API should now be fully documented -- it doesn't mean that all TODOs are gone, but we're getting there :-)

2021-09-10 13:40 UTC, graemerocher requested changes
Looks fine, just one small typo I noticed

2021-09-10 13:42 UTC, Ladicek commented on api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SubtypesOf.java
> + * Constraints the {@link Enhancement @Enhancement} or {@link Processing @Processing} method to subtypes of given types.
Embarassing :-)

2021-09-10 13:44 UTC, Ladicek commented on api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SubtypesOf.java
> + * Constraints the {@link Enhancement @Enhancement} or {@link Processing @Processing} method to subtypes of given types.
Fixed.

2021-09-10 13:44 UTC, graemerocher commented on api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SubtypesOf.java
> + * Constraints the {@link Enhancement @Enhancement} or {@link Processing @Processing} method to subtypes of given types.
lol not really, would probably have made that typo myself if I was recently working with `javax.validation` :)

2021-09-13 11:22 UTC, manovotn approved these changes

2021-09-13 11:56 UTC, graemerocher approved these changes

2021-09-13 12:15 UTC, merged